name: OpenOffice Calc Evaluation

on:
  workflow_dispatch:
    inputs:
      lesson_name:
        description: 'Lesson Name (Optional)'
        required: false
        default: ''

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Requirements
        run: pip install -r requirements.txt

      - name: Run Evaluation Script
        run: python src/evaluation.py "${{ github.event.inputs.lesson_name }}"

      - name: Push and Commit Report
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add report_*.csv
          git commit -m "Add Evaluation Report for ${{ github.event.inputs.lesson_name }}"
          git push
